# CONFIGURE ACCORDING YOUR NEEDS
USERNAME = "YOURUSER@NAME"
PASSWORD= "YOURPASSWORD"
# YOUR WORK PLACE COORDINATES OR AREA OF INTEREST 
WORK_COORDINATES = ["20.6621985","-103.4068092"] 
# NUMBER OF PLACES TO FETCH
LIMIT = 2 
# MAX PRICE OF RENTING
MAX_PRICE = 4000 
#GOOGLE API KEY
API_KEY="YOUR_API_KEY" 
